stages:
  - test
  - release

.base:
  image: registry.gitlab.com/lumoslabs/docker-library/golang:1.12-ci
  variables:
    GOFLAGS: -mod=vendor

test:
  extends: .base
  stage: test
  script: make test

test:race:
  extends: .base
  stage: test
  script: make test-race

test:memory:
  extends: .base
  stage: test
  script: make test-memory

release:test:
  extends: .base
  stage: release
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$QUAY_PASSWORD" | docker login --username="$QUAY_USERNAME" --password-stdin quay.io
    - echo "$CI_JOB_TOKEN" | docker login --username=gitlab-ci-token --password-stdin $CI_REGISTRY
    - goreleaser release --rm-dist --snapshot

release:
  extends: .base
  stage: release
  only:
    - tags
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "$QUAY_PASSWORD" | docker login --username="$QUAY_USERNAME" --password-stdin quay.io
    - echo "$CI_JOB_TOKEN" | docker login --username=gitlab-ci-token --password-stdin $CI_REGISTRY
    - goreleaser release --rm-dist
