---
builds:
  - env: ["CGO_ENABLED=0"]
    main: ./cmd/vest
    binary: vest
    asmflags: ["all=-trimpath={{.Env.PWD}}"]
    gcflags: ["all=-trimpath={{.Env.PWD}}"]
  - env: ["CGO_ENABLED=0"]
    main: ./cmd/bule
    binary: bule
    asmflags: ["all=-trimpath={{.Env.PWD}}"]
    gcflags: ["all=-trimpath={{.Env.PWD}}"]

archives:
  - files: ["none*"]
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto

# brew:
#   skip_upload: auto
#   github:
#     owner: lumoslabs
#     name: homebrew-vestibule

#   folder: Formula
#   description: "Gather secrets from various backends and inject them into the process environment"
#   homepage: "https://github.com/lumoslabs/vestibule"
#   test: |
#     system "#{bin}/vest --version"
#     system "#{bin}/bule --version"

dockers:
  - dockerfile: docker/alpine/Dockerfile
    binaries: [bule, vest]
    image_templates:
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}-alpine"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}-alpine"

  - dockerfile: docker/ubuntu/bionic/Dockerfile
    binaries: [bule, vest]
    image_templates:
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}-bionic"
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}"
      - "quay.io/lumoslabs/vestibule:v{{ .Major }}.{{ .Minor }}"
      - "quay.io/lumoslabs/vestibule:latest"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}-bionic"
      - "registry.gitlab.com/lumoslabs/vestibule:v{{ .Major }}.{{ .Minor }}"
      - "registry.gitlab.com/lumoslabs/vestibule:latest"
