builds:
  - env: ["CGO_ENABLED=0"]
    main: ./cmd/vest
    binary: vest
    asmflags: ["all=-trimpath={{.Env.GOPATH}}"]
    gcflags: ["all=-trimpath={{.Env.GOPATH}}"]
archive:
  files: ["none*"]
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  prerelease: true
dockers:
  - dockerfile: docker/alpine/Dockerfile
    binaries: [vest]
    image_templates:
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}-alpine"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}-alpine"

  - dockerfile: docker/stretch/Dockerfile
    binaries: [vest]
    image_templates:
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}-stretch"
      - "quay.io/lumoslabs/vestibule:{{ .Tag }}"
      - "quay.io/lumoslabs/vestibule:latest"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}"
      - "registry.gitlab.com/lumoslabs/vestibule:{{ .Tag }}-stretch"
      - "registry.gitlab.com/lumoslabs/vestibule:latest"
